### ISSUE TITLE
Unable to generate clsp inplant or perform keygen

### ISSUE THREAD

**Issue by servebeer** [APT64/EternalHushFramework#7]
I have the framework working, but when I try to "prepare" the clsp implant nothing happens (Screenshot 1.png) I don't get any errors, but I don't get the prompt shown in the wiki. I also tried to run keygen (Sceenshot 2.png) but I have the same results, no errors but it doesn't appear to run.

[Screenshot 1.png]
![Screenshot 1](https://github.com/APT64/EternalHushFramework/assets/8514341/0da6d79a-e8b6-467d-9319-6cb7ddeed31d)

{Screenshot 2.png]
![Screenshot 2](https://github.com/APT64/EternalHushFramework/assets/8514341/e82ef400-0d84-4437-a254-98ee3e3b0c34)

**Comment by APT64** [comment]
Oh, good evening. Can you tell me what versions of java and python you have installed? I will also be finalizing the logging system very soon.

**Comment by APT64** [comment]
Also additionally check if modules and their scripts are in the build folder.

**Comment by servebeer** [comment]
Hello,
Sure... here are my version numbers:
Python: 3.10.1
Java: Java(TM) SE Runtime Environment 18.9 (build 11.0.15.1+2-LTS-10)

**Comment by servebeer** [comment]
![Screenshot 2023-09-05 141210](https://github.com/APT64/EternalHushFramework/assets/8514341/7ed2edbc-fbd9-4d8d-84dd-ec9e2576433d)

I'll go ahead and try a pre-compiled archive as well.

**Comment by APT64** [comment]
Ok, you can download it [here](https://github.com/APT64/EternalHushFramework/releases)

**Comment by servebeer** [comment]
Unfortunately I am having the same results with the pre-compiled code.

**Comment by servebeer** [comment]
will do...

**Comment by servebeer** [comment]
That got us about 99% there! The only issue I am seeing now is when I try to save a keypair for a newly generated clsp:

![Screenshot 2023-09-05 155226](https://github.com/APT64/EternalHushFramework/assets/8514341/217e117f-f310-4650-94cc-acae0d7c66d2)

Could this be due to the directory location? I am enclosing it in ""'s

**Comment by APT64** [comment]
Oh yes, at the moment the path must be specified without spaces and "". For example D:\Keys.

**Comment by servebeer** [comment]
Thanks for that info. I’ll go ahead and start “playing“  working with it.v/rJonOn Sep 5, 2023, at 16:05, APT64 ***@***.***> wrote:﻿
Oh yes, at the moment the path must be specified without spaces and "". For example D:\Keys.
